[2024-03-28T04:00:06.679+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_historical_congress_data.bq_create_bills_Congress_partitioned_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-28T04:00:06.689+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_historical_congress_data.bq_create_bills_Congress_partitioned_table_task scheduled__2024-03-15T00:00:00+00:00 [queued]>
[2024-03-28T04:00:06.691+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-28T04:00:06.703+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_bills_Congress_partitioned_table_task> on 2024-03-15 00:00:00+00:00
[2024-03-28T04:00:06.710+0000] {standard_task_runner.py:60} INFO - Started process 144 to run task
[2024-03-28T04:00:06.713+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_historical_congress_data', 'bq_create_bills_Congress_partitioned_table_task', 'scheduled__2024-03-15T00:00:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/upload_historical_congress_data.py', '--cfg-path', '/tmp/tmpp5cbgeqj']
[2024-03-28T04:00:06.718+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask bq_create_bills_Congress_partitioned_table_task
[2024-03-28T04:00:06.771+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_historical_congress_data.bq_create_bills_Congress_partitioned_table_task scheduled__2024-03-15T00:00:00+00:00 [running]> on host be5d54f7fe24
[2024-03-28T04:00:06.830+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_historical_congress_data' AIRFLOW_CTX_TASK_ID='bq_create_bills_Congress_partitioned_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-15T00:00:00+00:00'
[2024-03-28T04:00:06.835+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-03-28T04:00:06.838+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-28T04:00:06.842+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-03-28T04:00:06.891+0000] {bigquery.py:2811} INFO - Executing: {'query': {'query': 'CREATE OR REPLACE TABLE Congress.bills         PARTITION BY updateDate_formatted         AS         SELECT *, DATE(updateDate) updateDate_formatted         FROM Congress.bills_external_table;', 'useLegacySql': False}}'
[2024-03-28T04:00:06.892+0000] {bigquery.py:1613} INFO - Inserting job ***_upload_historical_congress_data_bq_create_bills_Congress_partitioned_table_task_2024_03_15T00_00_00_00_00_4590a4561e1eb451dc4fe3dc36e1e10b
[2024-03-28T04:00:09.134+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2870, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: Congress.bills_external_table, error message: Parquet column 'latestAction.actionDate' has type BYTE_ARRAY which does not match the target cpp_type INT32. File: gs://congress_data/bills/1251_1500_bills.parquet; reason: invalid, location: gs://congress_data/bills/1251_1500_bills.parquet, message: Error while reading table: Congress.bills_external_table, error message: Parquet column 'latestAction.actionDate' has type BYTE_ARRAY which does not match the target cpp_type INT32. File: gs://congress_data/bills/1251_1500_bills.parquet

Location: US
Job ID: airflow_upload_historical_congress_data_bq_create_bills_Congress_partitioned_table_task_2024_03_15T00_00_00_00_00_4590a4561e1eb451dc4fe3dc36e1e10b

[2024-03-28T04:00:09.152+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=upload_historical_congress_data, task_id=bq_create_bills_Congress_partitioned_table_task, execution_date=20240315T000000, start_date=20240328T040006, end_date=20240328T040009
[2024-03-28T04:00:09.164+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 185 for task bq_create_bills_Congress_partitioned_table_task (400 Error while reading table: Congress.bills_external_table, error message: Parquet column 'latestAction.actionDate' has type BYTE_ARRAY which does not match the target cpp_type INT32. File: gs://congress_data/bills/1251_1500_bills.parquet; reason: invalid, location: gs://congress_data/bills/1251_1500_bills.parquet, message: Error while reading table: Congress.bills_external_table, error message: Parquet column 'latestAction.actionDate' has type BYTE_ARRAY which does not match the target cpp_type INT32. File: gs://congress_data/bills/1251_1500_bills.parquet

Location: US
Job ID: airflow_upload_historical_congress_data_bq_create_bills_Congress_partitioned_table_task_2024_03_15T00_00_00_00_00_4590a4561e1eb451dc4fe3dc36e1e10b
; 144)
[2024-03-28T04:00:09.198+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-28T04:00:09.213+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
