[2024-03-30T00:00:26.389+0000] {processor.py:161} INFO - Started process (PID=2081) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:00:26.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:00:26.399+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:00:26.398+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:00:26.451+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:00:26.450+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:00:26.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:00:26.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.100 seconds
[2024-03-30T00:00:56.867+0000] {processor.py:161} INFO - Started process (PID=2088) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:00:56.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:00:56.895+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:00:56.892+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:00:56.952+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:00:56.951+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:00:56.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:00:56.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.107 seconds
[2024-03-30T00:01:27.373+0000] {processor.py:161} INFO - Started process (PID=2095) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:01:27.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:01:27.380+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:01:27.379+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:01:27.426+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:01:27.425+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:01:27.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:01:27.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.088 seconds
[2024-03-30T00:01:57.973+0000] {processor.py:161} INFO - Started process (PID=2102) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:01:57.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:01:57.980+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:01:57.979+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:01:58.052+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:01:58.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:01:58.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:01:58.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.120 seconds
[2024-03-30T00:02:28.306+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:02:28.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:02:28.319+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:02:28.319+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:02:28.358+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:02:28.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:02:28.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:02:28.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.071 seconds
[2024-03-30T00:02:58.639+0000] {processor.py:161} INFO - Started process (PID=2117) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:02:58.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:02:58.644+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:02:58.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:02:58.706+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:02:58.705+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:02:58.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:02:58.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.087 seconds
[2024-03-30T00:03:29.033+0000] {processor.py:161} INFO - Started process (PID=2124) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:03:29.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:03:29.037+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:03:29.036+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:03:29.100+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:03:29.098+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:03:29.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:03:29.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.086 seconds
[2024-03-30T00:03:59.474+0000] {processor.py:161} INFO - Started process (PID=2131) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:03:59.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:03:59.479+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:03:59.478+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:03:59.531+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:03:59.530+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:03:59.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:03:59.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.089 seconds
[2024-03-30T00:04:29.917+0000] {processor.py:161} INFO - Started process (PID=2138) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:04:29.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:04:29.924+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:04:29.923+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:04:29.989+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:04:29.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:04:29.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:04:30.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.093 seconds
[2024-03-30T00:05:00.361+0000] {processor.py:161} INFO - Started process (PID=2145) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:05:00.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:05:00.373+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:05:00.372+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:05:00.424+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:05:00.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:05:00.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:05:00.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.095 seconds
[2024-03-30T00:05:30.749+0000] {processor.py:161} INFO - Started process (PID=2152) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:05:30.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:05:30.755+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:05:30.754+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:05:30.807+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:05:30.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:05:30.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:05:30.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.080 seconds
[2024-03-30T00:06:01.168+0000] {processor.py:161} INFO - Started process (PID=2159) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:06:01.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:06:01.178+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:06:01.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:06:01.274+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:06:01.272+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:06:01.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:06:01.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.171 seconds
[2024-03-30T00:06:31.466+0000] {processor.py:161} INFO - Started process (PID=2166) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:06:31.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:06:31.472+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:06:31.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:06:31.586+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:06:31.581+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:06:31.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:06:31.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.174 seconds
[2024-03-30T00:07:01.977+0000] {processor.py:161} INFO - Started process (PID=2173) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:01.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:07:01.983+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:07:01.982+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:02.057+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:07:02.056+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:07:02.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:02.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.108 seconds
[2024-03-30T00:07:32.287+0000] {processor.py:161} INFO - Started process (PID=2180) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:32.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:07:32.294+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:07:32.293+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:32.366+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:07:32.365+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 142, in <module>
    PARTITION BY {DATE_COLS[data_type]}_formatted \
                  ~~~~~~~~~^^^^^^^^^^^
KeyError: 'votes'
[2024-03-30T00:07:32.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:32.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.106 seconds
[2024-03-30T00:07:58.586+0000] {processor.py:161} INFO - Started process (PID=2187) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:58.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:07:58.593+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:07:58.593+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:58.602+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:07:58.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 24
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:07:58.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:07:58.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.044 seconds
[2024-03-30T00:08:17.777+0000] {processor.py:161} INFO - Started process (PID=2193) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:08:17.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:08:17.781+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:08:17.780+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:08:17.787+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:08:17.786+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 24
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:08:17.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:08:17.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.037 seconds
[2024-03-30T00:08:48.074+0000] {processor.py:161} INFO - Started process (PID=2200) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:08:48.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:08:48.081+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:08:48.080+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:08:48.091+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:08:48.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 24
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:08:48.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:08:48.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.045 seconds
[2024-03-30T00:09:18.442+0000] {processor.py:161} INFO - Started process (PID=2207) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:09:18.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:09:18.448+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:09:18.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:09:18.457+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:09:18.456+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 24
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:09:18.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:09:18.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.053 seconds
[2024-03-30T00:09:48.771+0000] {processor.py:161} INFO - Started process (PID=2214) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:09:48.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:09:48.778+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:09:48.777+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:09:48.788+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:09:48.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 24
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:09:48.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:09:48.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.043 seconds
[2024-03-30T00:10:06.049+0000] {processor.py:161} INFO - Started process (PID=2215) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:10:06.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:10:06.054+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:10:06.053+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:10:06.061+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:10:06.060+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:10:06.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:10:06.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.038 seconds
[2024-03-30T00:10:36.422+0000] {processor.py:161} INFO - Started process (PID=2222) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:10:36.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:10:36.428+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:10:36.428+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:10:36.437+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:10:36.436+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:10:36.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:10:36.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.042 seconds
[2024-03-30T00:11:06.878+0000] {processor.py:161} INFO - Started process (PID=2229) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:11:06.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:11:06.884+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:11:06.884+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:11:06.894+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:11:06.892+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:11:06.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:11:06.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.060 seconds
[2024-03-30T00:11:37.611+0000] {processor.py:161} INFO - Started process (PID=2236) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:11:37.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:11:37.623+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:11:37.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:11:37.641+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:11:37.639+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:11:37.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:11:37.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.060 seconds
[2024-03-30T00:12:07.972+0000] {processor.py:161} INFO - Started process (PID=2243) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:12:07.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:12:07.978+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:12:07.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:12:07.985+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:12:07.985+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:12:07.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:12:07.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.035 seconds
[2024-03-30T00:12:38.283+0000] {processor.py:161} INFO - Started process (PID=2250) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:12:38.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:12:38.289+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:12:38.288+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:12:38.297+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:12:38.296+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:12:38.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:12:38.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.049 seconds
[2024-03-30T00:13:08.629+0000] {processor.py:161} INFO - Started process (PID=2263) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:13:08.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:13:08.634+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:13:08.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:13:08.642+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:13:08.641+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:13:08.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:13:08.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.037 seconds
[2024-03-30T00:13:38.993+0000] {processor.py:161} INFO - Started process (PID=2270) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:13:38.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:13:39.000+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:13:38.999+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:13:39.010+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:13:39.008+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:13:39.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:13:39.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.044 seconds
[2024-03-30T00:14:09.355+0000] {processor.py:161} INFO - Started process (PID=2277) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:14:09.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:14:09.360+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:14:09.359+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:14:09.366+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:14:09.365+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:14:09.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:14:09.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.034 seconds
[2024-03-30T00:14:39.748+0000] {processor.py:161} INFO - Started process (PID=2284) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:14:39.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:14:39.751+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:14:39.751+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:14:39.757+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:14:39.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:14:39.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:14:39.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.028 seconds
[2024-03-30T00:15:10.379+0000] {processor.py:161} INFO - Started process (PID=2291) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:15:10.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:15:10.389+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:15:10.388+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:15:10.405+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:15:10.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:15:10.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:15:10.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.075 seconds
[2024-03-30T00:15:40.756+0000] {processor.py:161} INFO - Started process (PID=2298) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:15:40.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:15:40.760+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:15:40.760+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:15:40.768+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:15:40.767+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:15:40.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:15:40.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.032 seconds
[2024-03-30T00:16:11.077+0000] {processor.py:161} INFO - Started process (PID=2305) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:16:11.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:16:11.085+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:16:11.084+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:16:11.094+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:16:11.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:16:11.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:16:11.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.060 seconds
[2024-03-30T00:16:41.338+0000] {processor.py:161} INFO - Started process (PID=2312) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:16:41.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:16:41.343+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:16:41.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:16:41.351+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:16:41.350+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:16:41.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:16:41.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.036 seconds
[2024-03-30T00:17:11.732+0000] {processor.py:161} INFO - Started process (PID=2319) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:17:11.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:17:11.739+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:17:11.738+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:17:11.748+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:17:11.747+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:17:11.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:17:11.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.042 seconds
[2024-03-30T00:17:42.119+0000] {processor.py:161} INFO - Started process (PID=2326) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:17:42.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:17:42.125+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:17:42.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:17:42.133+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:17:42.132+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:17:42.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:17:42.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.038 seconds
[2024-03-30T00:18:12.533+0000] {processor.py:161} INFO - Started process (PID=2333) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:18:12.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:18:12.541+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:18:12.540+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:18:12.552+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:18:12.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:18:12.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:18:12.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.050 seconds
[2024-03-30T00:18:42.967+0000] {processor.py:161} INFO - Started process (PID=2340) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:18:42.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:18:42.972+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:18:42.971+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:18:42.980+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:18:42.979+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:18:42.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:18:42.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.038 seconds
[2024-03-30T00:19:13.445+0000] {processor.py:161} INFO - Started process (PID=2347) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:19:13.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:19:13.452+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:19:13.451+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:19:13.463+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:19:13.461+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:19:13.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:19:13.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.045 seconds
[2024-03-30T00:19:43.853+0000] {processor.py:161} INFO - Started process (PID=2353) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:19:43.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:19:43.858+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:19:43.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:19:43.867+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:19:43.865+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:19:43.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:19:43.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.039 seconds
[2024-03-30T00:20:14.311+0000] {processor.py:161} INFO - Started process (PID=2360) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:20:14.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:20:14.317+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:20:14.316+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:20:14.326+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:20:14.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:20:14.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:20:14.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.048 seconds
[2024-03-30T00:20:44.650+0000] {processor.py:161} INFO - Started process (PID=2366) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:20:44.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:20:44.652+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:20:44.652+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:20:44.656+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:20:44.656+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:20:44.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:20:44.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.023 seconds
[2024-03-30T00:21:15.152+0000] {processor.py:161} INFO - Started process (PID=2373) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:21:15.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:21:15.159+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:21:15.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:21:15.180+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:21:15.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:21:15.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:21:15.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.065 seconds
[2024-03-30T00:21:45.626+0000] {processor.py:161} INFO - Started process (PID=2380) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:21:45.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:21:45.633+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:21:45.633+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:21:45.643+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:21:45.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:21:45.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:21:45.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.046 seconds
[2024-03-30T00:22:16.086+0000] {processor.py:161} INFO - Started process (PID=2387) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:22:16.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:22:16.092+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:22:16.091+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:22:16.101+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:22:16.100+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:22:16.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:22:16.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.055 seconds
[2024-03-30T00:22:46.514+0000] {processor.py:161} INFO - Started process (PID=2394) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:22:46.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:22:46.521+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:22:46.520+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:22:46.531+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:22:46.529+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:22:46.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:22:46.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.048 seconds
[2024-03-30T00:23:17.214+0000] {processor.py:161} INFO - Started process (PID=2401) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:23:17.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:23:17.220+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:23:17.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:23:17.241+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:23:17.239+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:23:17.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:23:17.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.052 seconds
[2024-03-30T00:23:47.656+0000] {processor.py:161} INFO - Started process (PID=2408) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:23:47.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:23:47.663+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:23:47.662+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:23:47.672+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:23:47.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:23:47.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:23:47.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.044 seconds
[2024-03-30T00:24:18.346+0000] {processor.py:161} INFO - Started process (PID=2415) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:24:18.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:24:18.354+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:24:18.353+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:24:18.363+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:24:18.362+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:24:18.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:24:18.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.046 seconds
[2024-03-30T00:24:48.806+0000] {processor.py:161} INFO - Started process (PID=2422) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:24:48.808+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:24:48.813+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:24:48.813+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:24:48.822+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:24:48.821+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:24:48.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:24:48.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.041 seconds
[2024-03-30T00:25:19.384+0000] {processor.py:161} INFO - Started process (PID=2429) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:25:19.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:25:19.391+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:25:19.391+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:25:19.400+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:25:19.398+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:25:19.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:25:19.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.044 seconds
[2024-03-30T00:41:11.995+0000] {processor.py:161} INFO - Started process (PID=2430) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:41:12.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:41:12.010+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:41:12.010+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:41:12.027+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:41:12.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:41:12.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:41:12.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.132 seconds
[2024-03-30T00:41:42.434+0000] {processor.py:161} INFO - Started process (PID=2437) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:41:42.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:41:42.441+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:41:42.440+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:41:42.450+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:41:42.449+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:41:42.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:41:42.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.050 seconds
[2024-03-30T00:42:12.803+0000] {processor.py:161} INFO - Started process (PID=2444) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:42:12.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:42:12.820+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:42:12.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:42:12.839+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:42:12.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:42:12.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:42:12.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.059 seconds
[2024-03-30T00:58:08.753+0000] {processor.py:161} INFO - Started process (PID=2451) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:58:08.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:58:08.759+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:08.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:58:08.772+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:08.769+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:58:08.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:58:08.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.080 seconds
[2024-03-30T00:58:39.744+0000] {processor.py:161} INFO - Started process (PID=2458) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:58:39.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T00:58:39.766+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:39.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:58:39.776+0000] {logging_mixin.py:188} INFO - [2024-03-30T00:58:39.774+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T00:58:39.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T00:58:39.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.083 seconds
[2024-03-30T01:16:03.776+0000] {processor.py:161} INFO - Started process (PID=2465) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:16:03.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:16:03.802+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:16:03.800+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:16:03.828+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:16:03.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:16:03.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:16:03.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.147 seconds
[2024-03-30T01:16:34.260+0000] {processor.py:161} INFO - Started process (PID=2472) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:16:34.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:16:34.268+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:16:34.267+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:16:34.278+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:16:34.276+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:16:34.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:16:34.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.053 seconds
[2024-03-30T01:18:12.325+0000] {processor.py:161} INFO - Started process (PID=2479) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:18:12.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:18:12.330+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:18:12.330+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:18:12.337+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:18:12.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:18:12.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:18:12.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.035 seconds
[2024-03-30T01:23:10.755+0000] {processor.py:161} INFO - Started process (PID=2486) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:23:10.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:23:10.767+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:23:10.765+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:23:10.780+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:23:10.778+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:23:10.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:23:10.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.075 seconds
[2024-03-30T01:23:41.071+0000] {processor.py:161} INFO - Started process (PID=2493) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:23:41.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:23:41.089+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:23:41.087+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:23:41.108+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:23:41.106+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:23:41.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:23:41.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.089 seconds
[2024-03-30T01:24:11.445+0000] {processor.py:161} INFO - Started process (PID=2500) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:11.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:24:11.450+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:11.450+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:11.457+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:11.456+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:24:11.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:11.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.035 seconds
[2024-03-30T01:24:41.820+0000] {processor.py:161} INFO - Started process (PID=2507) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:41.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:24:41.830+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:41.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:41.846+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:41.844+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:24:41.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:41.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.062 seconds
[2024-03-30T01:24:43.860+0000] {processor.py:161} INFO - Started process (PID=2514) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:43.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:24:43.863+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:43.863+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:43.869+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:43.868+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:24:43.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:43.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.029 seconds
[2024-03-30T01:24:44.902+0000] {processor.py:161} INFO - Started process (PID=2515) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:44.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:24:44.907+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:44.906+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:44.916+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:24:44.915+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:24:44.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:24:44.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.037 seconds
[2024-03-30T01:25:15.218+0000] {processor.py:161} INFO - Started process (PID=2522) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:25:15.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:25:15.223+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:25:15.222+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:25:15.231+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:25:15.230+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:25:15.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:25:15.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.038 seconds
[2024-03-30T01:25:45.532+0000] {processor.py:161} INFO - Started process (PID=2529) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:25:45.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:25:45.546+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:25:45.545+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:25:45.556+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:25:45.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:25:45.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:25:45.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.067 seconds
[2024-03-30T01:26:15.830+0000] {processor.py:161} INFO - Started process (PID=2536) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:26:15.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:26:15.838+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:26:15.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:26:15.849+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:26:15.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:26:15.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:26:15.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.052 seconds
[2024-03-30T01:26:46.585+0000] {processor.py:161} INFO - Started process (PID=2543) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:26:46.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:26:46.591+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:26:46.591+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:26:46.616+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:26:46.613+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:26:46.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:26:46.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.071 seconds
[2024-03-30T01:27:17.026+0000] {processor.py:161} INFO - Started process (PID=2550) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:27:17.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:27:17.035+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:27:17.034+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:27:17.054+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:27:17.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:27:17.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:27:17.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.058 seconds
[2024-03-30T01:27:47.660+0000] {processor.py:161} INFO - Started process (PID=2557) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:27:47.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T01:27:47.667+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:27:47.666+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:27:47.675+0000] {logging_mixin.py:188} INFO - [2024-03-30T01:27:47.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T01:27:47.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T01:27:47.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.059 seconds
[2024-03-30T02:46:29.312+0000] {processor.py:161} INFO - Started process (PID=2558) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T02:46:29.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T02:46:29.317+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:46:29.317+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T02:46:29.324+0000] {logging_mixin.py:188} INFO - [2024-03-30T02:46:29.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T02:46:29.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T02:46:29.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.053 seconds
[2024-03-30T04:00:56.110+0000] {processor.py:161} INFO - Started process (PID=2564) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T04:00:56.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T04:00:56.152+0000] {logging_mixin.py:188} INFO - [2024-03-30T04:00:56.151+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T04:00:56.167+0000] {logging_mixin.py:188} INFO - [2024-03-30T04:00:56.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T04:00:56.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T04:00:56.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.168 seconds
[2024-03-30T05:26:39.358+0000] {processor.py:161} INFO - Started process (PID=2571) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T05:26:39.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T05:26:39.370+0000] {logging_mixin.py:188} INFO - [2024-03-30T05:26:39.369+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T05:26:39.398+0000] {logging_mixin.py:188} INFO - [2024-03-30T05:26:39.394+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T05:26:39.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T05:26:39.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.129 seconds
[2024-03-30T06:50:21.696+0000] {processor.py:161} INFO - Started process (PID=2578) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T06:50:21.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T06:50:21.700+0000] {logging_mixin.py:188} INFO - [2024-03-30T06:50:21.700+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T06:50:21.706+0000] {logging_mixin.py:188} INFO - [2024-03-30T06:50:21.705+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T06:50:21.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T06:50:21.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.028 seconds
[2024-03-30T08:12:12.523+0000] {processor.py:161} INFO - Started process (PID=2585) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T08:12:12.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T08:12:12.531+0000] {logging_mixin.py:188} INFO - [2024-03-30T08:12:12.531+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T08:12:12.536+0000] {logging_mixin.py:188} INFO - [2024-03-30T08:12:12.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T08:12:12.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T08:12:12.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.034 seconds
[2024-03-30T09:52:10.987+0000] {processor.py:161} INFO - Started process (PID=2592) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T09:52:10.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T09:52:11.002+0000] {logging_mixin.py:188} INFO - [2024-03-30T09:52:11.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T09:52:11.030+0000] {logging_mixin.py:188} INFO - [2024-03-30T09:52:11.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T09:52:11.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T09:52:11.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.139 seconds
[2024-03-30T11:13:24.889+0000] {processor.py:161} INFO - Started process (PID=2599) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T11:13:24.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T11:13:24.901+0000] {logging_mixin.py:188} INFO - [2024-03-30T11:13:24.899+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T11:13:24.943+0000] {logging_mixin.py:188} INFO - [2024-03-30T11:13:24.941+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T11:13:24.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T11:13:25.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.136 seconds
[2024-03-30T12:48:51.158+0000] {processor.py:161} INFO - Started process (PID=2606) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T12:48:51.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T12:48:51.165+0000] {logging_mixin.py:188} INFO - [2024-03-30T12:48:51.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T12:48:51.174+0000] {logging_mixin.py:188} INFO - [2024-03-30T12:48:51.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T12:48:51.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T12:48:51.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.042 seconds
[2024-03-30T13:57:44.548+0000] {processor.py:161} INFO - Started process (PID=2613) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T13:57:44.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T13:57:44.552+0000] {logging_mixin.py:188} INFO - [2024-03-30T13:57:44.552+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T13:57:44.558+0000] {logging_mixin.py:188} INFO - [2024-03-30T13:57:44.557+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T13:57:44.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T13:57:44.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.031 seconds
[2024-03-30T14:34:33.239+0000] {processor.py:161} INFO - Started process (PID=2620) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T14:34:33.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T14:34:33.261+0000] {logging_mixin.py:188} INFO - [2024-03-30T14:34:33.259+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T14:34:33.338+0000] {logging_mixin.py:188} INFO - [2024-03-30T14:34:33.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T14:34:33.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T14:34:33.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.197 seconds
[2024-03-30T15:52:48.011+0000] {processor.py:161} INFO - Started process (PID=2627) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T15:52:48.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T15:52:48.024+0000] {logging_mixin.py:188} INFO - [2024-03-30T15:52:48.023+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T15:52:48.049+0000] {logging_mixin.py:188} INFO - [2024-03-30T15:52:48.045+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T15:52:48.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T15:52:48.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.129 seconds
[2024-03-30T16:19:06.177+0000] {processor.py:161} INFO - Started process (PID=2633) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T16:19:06.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T16:19:06.197+0000] {logging_mixin.py:188} INFO - [2024-03-30T16:19:06.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T16:19:06.217+0000] {logging_mixin.py:188} INFO - [2024-03-30T16:19:06.215+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T16:19:06.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T16:19:06.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.117 seconds
[2024-03-30T17:20:08.516+0000] {processor.py:161} INFO - Started process (PID=2640) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T17:20:08.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T17:20:08.520+0000] {logging_mixin.py:188} INFO - [2024-03-30T17:20:08.519+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T17:20:08.525+0000] {logging_mixin.py:188} INFO - [2024-03-30T17:20:08.524+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T17:20:08.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T17:20:08.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.046 seconds
[2024-03-30T18:53:54.204+0000] {processor.py:161} INFO - Started process (PID=2647) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T18:53:54.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T18:53:54.218+0000] {logging_mixin.py:188} INFO - [2024-03-30T18:53:54.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T18:53:54.231+0000] {logging_mixin.py:188} INFO - [2024-03-30T18:53:54.229+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T18:53:54.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T18:53:54.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.080 seconds
[2024-03-30T20:11:14.165+0000] {processor.py:161} INFO - Started process (PID=2654) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T20:11:14.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T20:11:14.169+0000] {logging_mixin.py:188} INFO - [2024-03-30T20:11:14.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T20:11:14.174+0000] {logging_mixin.py:188} INFO - [2024-03-30T20:11:14.173+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T20:11:14.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T20:11:14.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.027 seconds
[2024-03-30T21:24:06.254+0000] {processor.py:161} INFO - Started process (PID=2661) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T21:24:06.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T21:24:06.262+0000] {logging_mixin.py:188} INFO - [2024-03-30T21:24:06.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T21:24:06.271+0000] {logging_mixin.py:188} INFO - [2024-03-30T21:24:06.269+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T21:24:06.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T21:24:06.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.040 seconds
[2024-03-30T22:40:37.701+0000] {processor.py:161} INFO - Started process (PID=2668) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T22:40:37.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T22:40:37.706+0000] {logging_mixin.py:188} INFO - [2024-03-30T22:40:37.706+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T22:40:37.712+0000] {logging_mixin.py:188} INFO - [2024-03-30T22:40:37.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T22:40:37.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T22:40:37.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.027 seconds
[2024-03-30T23:59:18.433+0000] {processor.py:161} INFO - Started process (PID=2675) to work on /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T23:59:18.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/upload_historical_congress_data.py for tasks to queue
[2024-03-30T23:59:18.447+0000] {logging_mixin.py:188} INFO - [2024-03-30T23:59:18.446+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T23:59:18.464+0000] {logging_mixin.py:188} INFO - [2024-03-30T23:59:18.461+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/upload_historical_congress_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/upload_historical_congress_data.py", line 25
    'house_votes': {'schema': house_vote_schema 'format':'JSON'}}
                                                ^^^^^^^^
SyntaxError: invalid syntax
[2024-03-30T23:59:18.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/upload_historical_congress_data.py
[2024-03-30T23:59:18.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/upload_historical_congress_data.py took 0.098 seconds
