[2024-07-01T02:41:13.456+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_congress_data.bq_create_senate_ids_external_table_task scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-01T02:41:13.470+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_congress_data.bq_create_senate_ids_external_table_task scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-01T02:41:13.470+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-07-01T02:41:13.482+0000] {taskinstance.py:2217} INFO - Executing <Task(BigQueryInsertJobOperator): bq_create_senate_ids_external_table_task> on 2024-06-30 00:00:00+00:00
[2024-07-01T02:41:13.493+0000] {standard_task_runner.py:60} INFO - Started process 169 to run task
[2024-07-01T02:41:13.505+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'upload_congress_data', 'bq_create_senate_ids_external_table_task', 'scheduled__2024-06-30T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/upload_congress_data.py', '--cfg-path', '/tmp/tmp988z1y0h']
[2024-07-01T02:41:13.517+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask bq_create_senate_ids_external_table_task
[2024-07-01T02:41:13.584+0000] {task_command.py:423} INFO - Running <TaskInstance: upload_congress_data.bq_create_senate_ids_external_table_task scheduled__2024-06-30T00:00:00+00:00 [running]> on host 0344fe541aae
[2024-07-01T02:41:13.649+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_congress_data' AIRFLOW_CTX_TASK_ID='bq_create_senate_ids_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T00:00:00+00:00'
[2024-07-01T02:41:13.651+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-01T02:41:13.652+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-07-01T02:41:13.653+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-07-01T02:41:13.712+0000] {bigquery.py:2811} INFO - Executing: {'query': {'query': "REATE OR REPLACE EXTERNAL TABLE Congress.senate_id_external_table (\n  first_name STRING,\n  last_name STRING,\n  state STRING,\n  bioguideID STRING,\n  lisid STRING\n)\nOPTIONS(\n  format = 'JSON',\n  uris = ['gs://congress_data_testproject-420401/members/senate_ids.json']\n  )", 'useLegacySql': False}}'
[2024-07-01T02:41:13.714+0000] {bigquery.py:1613} INFO - Inserting job ***_upload_congress_data_bq_create_senate_ids_external_table_task_2024_06_30T00_00_00_00_00_41cbdeef5cf027d2c32fd69d6f30cbdb
[2024-07-01T02:41:14.526+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2870, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected identifier "REATE" at [1:1]; reason: invalidQuery, location: query, message: Syntax error: Unexpected identifier "REATE" at [1:1]

Location: US
Job ID: airflow_upload_congress_data_bq_create_senate_ids_external_table_task_2024_06_30T00_00_00_00_00_41cbdeef5cf027d2c32fd69d6f30cbdb

[2024-07-01T02:41:14.539+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_congress_data, task_id=bq_create_senate_ids_external_table_task, execution_date=20240630T000000, start_date=20240701T024113, end_date=20240701T024114
[2024-07-01T02:41:14.548+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task bq_create_senate_ids_external_table_task (400 Syntax error: Unexpected identifier "REATE" at [1:1]; reason: invalidQuery, location: query, message: Syntax error: Unexpected identifier "REATE" at [1:1]

Location: US
Job ID: airflow_upload_congress_data_bq_create_senate_ids_external_table_task_2024_06_30T00_00_00_00_00_41cbdeef5cf027d2c32fd69d6f30cbdb
; 169)
[2024-07-01T02:41:14.591+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-01T02:41:14.614+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
